name: Deploy DocC Documentation to Github Pages
on:
  # Runs on pushes targeting the master branch
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
  
jobs:
  # One deployment deploy job since we're just deploying
  deploy:
    environment:
      # Must set to this for deploying to GitHub Pages
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
      - name: Build docs
        # uses: 0xWDG/build-documentation@0.1.1
        # with:
        #   iOS: true
        uses: sersoft-gmbh/swifty-docs-action@v3
        with:
          output: docs
          transform-for-static-hosting: true
          enable-index-building: true
          enable-inherited-docs: true
          hosting-base-path: "Extension"
          use-xcodebuild: true
          xcodebuild-destination: "generic/platform=iOS"
          xcodebuild-scheme: "Extension"
      - name: Build Jekyll for GitHub Pages
        uses: actions/jekyll-build-pages@v1
        with:
          source: "./docs"
          verbose: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
